export const GET_ARTICLES ='GET_ARTICLES'
export const ARTICLES_NEXT_PAGE ="ARTICLES_NEXT_PAGE"
export const ARTICLES_PREVIOUS_PAGE="ARTICLES_PREVIOUS_PAGE"
export const ARTICLES_SET_TOTAL_PAGE="ARTICLES_SET_TOTAL_PAGE"
export const ARTICLES_SET_ARTICLES ="ARTICLES_SET_ARTICLES";

//login
export const LOGIN_SUCCESS ="LOGIN_SUCCESS";
export const LOGIN_ERRORS_EMAIL_EMPTY="LOGIN_ERRORS_EMAIL_EMPTY";
export const LOGIN_ERRORS_EMAIL_WRONG_TYPE="LOGIN_ERRORS_EMAIL_WRONG_TYPE";
export const LOGIN_ERRORS_PASSWORD_EMPTY="LOGIN_ERRORS_PASSWORD_EMPTY"
export const LOGIN_ERRORS_EMAIL_NOT_EXIT="LOGIN_ERRORS_EMAIL_NOT_EXIT";
export const LOGIN_ERRORS_PASSWORD_ERROR="LOGIN_ERRORS_PASSWORD_ERROR";

//logout
export const LOGOUT_SUCCESS ="LOGOUT_SUCCESS";


//notebooks
export const NOTEBOOKS_GET_ALL="NOTEBOOKS_GET_ALL";

//notebook
export const NOTEBOOK_CREATE_SUCCESS="NOTEBOOK_CREATE_SUCCESS";
export const NOTEBOOK_NEW_GET_ID_SUCCESS ="NOTEBOOK_NEW_GET_ID_SUCCESS";
export const NOTEBOOK_UPDATE_SUCCESS ="NOTEBOOK_UPDATE_SUCCESS";